"""Impact Matrix view — searchable reverse dependency table."""

from __future__ import annotations

import pandas as pd
import streamlit as st

from viz.components.file_viewer import file_viewer


def render(_configs: dict, _tables: dict, _graph: dict, matrix: list) -> None:
    st.header("Impact Matrix")
    st.caption(
        "If you change a file, what flows and DB tables are affected? "
        "Auto-generated by inverting the dependency graph."
    )

    df = pd.DataFrame(matrix)
    df = df.rename(
        columns={
            "file": "If you change...",
            "type": "Type",
            "flows": "Flows affected",
            "tables": "DB tables",
            "fields": "Fields",
        }
    )

    # Filters
    col1, col2 = st.columns([3, 1])
    with col1:
        search = st.text_input(
            "Search",
            key="impact_search",
            placeholder="e.g. brain_dump, scoring, items",
        )
    with col2:
        types = sorted(df["Type"].unique())
        type_filter = st.multiselect("Filter by type", options=types, key="impact_type")

    # Apply filters
    filtered = df
    if search:
        mask = filtered.apply(
            lambda row: any(search.lower() in str(v).lower() for v in row),
            axis=1,
        )
        filtered = filtered[mask]
    if type_filter:
        filtered = filtered[filtered["Type"].isin(type_filter)]

    # Stats
    st.markdown(
        f"**{len(filtered)}** of {len(df)} entries"
        + (f" matching `{search}`" if search else "")
    )

    # Display
    st.dataframe(
        filtered,
        width="stretch",
        hide_index=True,
        height=min(len(filtered) * 35 + 38, 800),
        column_config={
            "If you change...": st.column_config.TextColumn(width="medium"),
            "Type": st.column_config.TextColumn(width="small"),
            "Flows affected": st.column_config.TextColumn(width="large"),
            "DB tables": st.column_config.TextColumn(width="medium"),
            "Fields": st.column_config.TextColumn(width="medium"),
        },
    )

    # Click a file to view
    st.divider()
    st.subheader("View File")
    file_names = sorted(df["If you change..."].unique())
    selected = st.selectbox(
        "Select a file to view its contents",
        options=[""] + file_names,
        key="impact_file_select",
    )
    if selected:
        # Resolve to actual path
        if selected.startswith("pipelines/"):
            rel_path = f"backend/config/{selected}"
        elif selected.endswith(".yaml"):
            rel_path = f"backend/config/{selected}"
        elif selected.endswith(".md"):
            rel_path = f"backend/prompts/{selected}"
        else:
            rel_path = selected
        file_viewer(rel_path)
